product:
  category: http://categories-api.default.svc.cluster.local:8080/api/v1/category/
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://test:Test123@mongodb.default.svc.cluster.local/OSC