spring:
  profiles: default
  application:
    name: products-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products-db
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://localhost:8083/api/v1/category/
  
---
spring:
  profiles: dev
  application:
    name: products-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products-dev-db
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://localhost:8083/api/v1/category/

---
spring:
  profiles: sit
  application:
    name: products-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products-sit-db
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://localhost:8083/api/v1/category/
  
---
spring:
  profiles: uat
  application:
    name: products-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products-uat-db
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://localhost:8083/api/v1/category/
  
---
spring:
  profiles: pat
  application:
    name: products-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products-pat-db
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://localhost:8083/api/v1/category/

---
spring: 
  profiles: prod
  application:
    name: products-api
  data:
    mongodb:
      uri: mongodb://test:Test123@mongodb.default.svc.cluster.local/OSC
server:
  host: http://products-api.default.svc.local 
  port: 8080
  servlet:
    context-path: /api/v1
products:
  category: http://categories-api.default.svc.cluster.local:8080/api/v1/category/